version: 3.5.10.{build}
image: Visual Studio 2017

branches:
  only:
    - master
configuration:
  - Production
environment:
  PROJECT: toofz.NecroDancer.Web.Api
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)

install:
  - nuget update -Self
  - git clone https://github.com/leonard-thieu/toofz-build.git Scripts

before_build:
  - appveyor-retry nuget restore -Verbosity quiet
build:
  project: $(PROJECT).sln
  publish_wap: true
  verbosity: minimal

test_script:
  - ps: .\Scripts\Test-Project.ps1
after_test:
  - ps: .\Scripts\Submit-CodeCoverageResults.ps1

deploy:
  - provider: Environment
    name: production
    on:
      appveyor_repo_tag: true