version: $(VersionPrefix).{build}
image: Visual Studio 2017

skip_branch_with_pr: true
skip_commits:
  files:
    - LICENSE
    - README.md
configuration:
  - Production
environment:
  VersionPrefix: 3.5.13
  VersionSuffix: 
  FileVersion: '%APPVEYOR_BUILD_VERSION%'
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(VersionPrefix)
  assembly_file_version: $(APPVEYOR_BUILD_VERSION)
  assembly_informational_version: $(VersionPrefix)$(VersionSuffix)

before_build:
  - nuget restore -Verbosity quiet
build:
  project: toofz.NecroDancer.Web.Api.sln
  publish_wap: true
  verbosity: quiet
  
test_script:
  - ps: |
      $projectPath = Resolve-Path .\test\toofz.NecroDancer.Web.Api.Tests\toofz.NecroDancer.Web.Api.Tests.csproj
      msbuild $projectPath /nologo /verbosity:minimal /target:Test

deploy:
  - provider: Environment
    name: production
    on:
      appveyor_repo_tag: true