version: 3.1.1.{build}
image: Visual Studio 2017

configuration:
  - Release
environment:
  PROJECT: toofz.NecroDancer.Web.Api
  COVERALLS_REPO_TOKEN:
    secure: Ai6MFECmpOwXY/YWeYyisOX1ysC/zYdRWmO5QmCWURkulMVKjRw54MxT5nMCt7rY
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_SERVICE_JOB_ID: '%APPVEYOR_JOB_ID%'
cache:
  - packages -> **\packages.config
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)

install:
  - git clone https://github.com/leonard-thieu/toofz-build.git Scripts

before_build:
  - appveyor-retry nuget restore -DisableParallelProcessing
build:
  project: $(PROJECT).sln
  publish_wap: true
  verbosity: minimal

test_script:
  - ps: .\Scripts\Test-Project.ps1 -Assembly $env:PROJECT
after_test:
  - ps: .\Scripts\Submit-CodeCoverageResults.ps1

deploy:
  - provider: Environment
    name: production
    on:
      appveyor_repo_tag: true