version: 3.1.2.{build}
image: Visual Studio 2017

configuration:
  - Release
environment:
  PROJECT: toofz.NecroDancer.Web.Api
cache:
  - packages -> **\packages.config
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)

install:
  - git clone https://github.com/leonard-thieu/toofz-build.git Scripts

before_build:
  - appveyor-retry nuget restore -Verbosity quiet
  - choco install opencover.portable --limit-output
  - choco install codecov --limit-output
build:
  project: $(PROJECT).sln
  publish_wap: true
  verbosity: minimal

test_script:
  - ps: .\Scripts\Test-Project.ps1
after_test:
  - codecov --file results.xml

deploy:
  - provider: Environment
    name: production
    on:
      appveyor_repo_tag: true