coverage:
  notify:
    slack:
      default:
        url: secret:c+EufeKxG6mcPB46Bz+e32fb2ghbV0HaR8KU2MOZC8VC6J2dYk8+J4zyyIHVZ69rD0aR6+p7yvdXBCu2g+rgFjmTMPptbOhDn+X4h+SgIpHBHhSrnMU1HCZ+JNcFxjCsW4F3Nfs5FCJVVouueTG02Rffark655h67IJ+PIWYTRU=
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null