//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toofz.NecroDancer.Web.Api.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("toofz.NecroDancer.Web.Api.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;total&quot;: 8,
        ///  &quot;enemies&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;bat&quot;,
        ///      &quot;type&quot;: 1,
        ///      &quot;display_name&quot;: &quot;Blue Bat&quot;,
        ///      &quot;health&quot;: 1,
        ///      &quot;damage&quot;: 1,
        ///      &quot;beats_per_move&quot;: 2,
        ///      &quot;drops&quot;: 2
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;dragon&quot;,
        ///      &quot;type&quot;: 2,
        ///      &quot;display_name&quot;: &quot;Red Dragon&quot;,
        ///      &quot;health&quot;: 6,
        ///      &quot;damage&quot;: 6,
        ///      &quot;beats_per_move&quot;: 2,
        ///      &quot;drops&quot;: 20
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;monkey&quot;,
        ///      &quot;type&quot;: 3,
        ///      &quot;display_name&quot;: &quot;Green Monkey&quot;,
        ///      &quot;health&quot;: 1,
        ///      &quot;dama [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEnemies {
            get {
                return ResourceManager.GetString("GetEnemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;total&quot;: 1,
        ///  &quot;enemies&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;necrodancer&quot;,
        ///      &quot;type&quot;: 1,
        ///      &quot;display_name&quot;: &quot;The Necrodancer&quot;,
        ///      &quot;health&quot;: 6,
        ///      &quot;damage&quot;: 3,
        ///      &quot;beats_per_move&quot;: 2,
        ///      &quot;drops&quot;: 0
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string GetEnemiesByAttribute {
            get {
                return ResourceManager.GetString("GetEnemiesByAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;total&quot;: 21,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;armor_glass&quot;,
        ///      &quot;display_name&quot;: &quot;Glass Armor&quot;,
        ///      &quot;slot&quot;: &quot;body&quot;,
        ///      &quot;unlock&quot;: 4,
        ///      &quot;cost&quot;: 50
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;feet_ballet_shoes&quot;,
        ///      &quot;display_name&quot;: &quot;Ballet Shoes&quot;,
        ///      &quot;slot&quot;: &quot;feet&quot;,
        ///      &quot;unlock&quot;: null,
        ///      &quot;cost&quot;: 25
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;food_1&quot;,
        ///      &quot;display_name&quot;: &quot;Apple&quot;,
        ///      &quot;slot&quot;: &quot;action&quot;,
        ///      &quot;unlock&quot;: null,
        ///      &quot;cost&quot;: 10
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;head_blast_helm&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItems {
            get {
                return ResourceManager.GetString("GetItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;total&quot;: 1,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;armor_glass&quot;,
        ///      &quot;display_name&quot;: &quot;Glass Armor&quot;,
        ///      &quot;slot&quot;: &quot;body&quot;,
        ///      &quot;unlock&quot;: 4,
        ///      &quot;cost&quot;: 50
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string GetItemsByCategory {
            get {
                return ResourceManager.GetString("GetItemsByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;total&quot;: 1,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;weapon_blood_bow&quot;,
        ///      &quot;display_name&quot;: &quot;Blood Bow&quot;,
        ///      &quot;slot&quot;: &quot;weapon&quot;,
        ///      &quot;unlock&quot;: null,
        ///      &quot;cost&quot;: 250
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string GetItemsBySubcategory {
            get {
                return ResourceManager.GetString("GetItemsBySubcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;total&quot;: 1,
        ///  &quot;leaderboards&quot;: [
        ///    {
        ///      &quot;id&quot;: 0,
        ///      &quot;updated_at&quot;: null,
        ///      &quot;display_name&quot;: null,
        ///      &quot;production&quot;: false,
        ///      &quot;product&quot;: &quot;amplified&quot;,
        ///      &quot;_product&quot;: {
        ///        &quot;id&quot;: 1,
        ///        &quot;name&quot;: &quot;amplified&quot;,
        ///        &quot;display_name&quot;: &quot;Amplified&quot;
        ///      },
        ///      &quot;mode&quot;: &quot;standard&quot;,
        ///      &quot;_mode&quot;: {
        ///        &quot;id&quot;: 0,
        ///        &quot;name&quot;: &quot;standard&quot;,
        ///        &quot;display_name&quot;: &quot;Standard&quot;
        ///      },
        ///      &quot;run&quot;: &quot;speed&quot;,
        ///      &quot;_run&quot;: {
        ///        &quot;id&quot;: 1,
        ///        &quot;name&quot;: &quot;speed&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetLeaderboards {
            get {
                return ResourceManager.GetString("GetLeaderboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;player&quot;: {
        ///    &quot;id&quot;: &quot;1&quot;,
        ///    &quot;updated_at&quot;: null,
        ///    &quot;display_name&quot;: &quot;Leonard&quot;,
        ///    &quot;avatar&quot;: null
        ///  },
        ///  &quot;total&quot;: 1,
        ///  &quot;entries&quot;: [
        ///    {
        ///      &quot;leaderboard&quot;: {
        ///        &quot;id&quot;: 739999,
        ///        &quot;updated_at&quot;: null,
        ///        &quot;display_name&quot;: null,
        ///        &quot;production&quot;: false,
        ///        &quot;product&quot;: &quot;classic&quot;,
        ///        &quot;_product&quot;: {
        ///          &quot;id&quot;: 1,
        ///          &quot;name&quot;: &quot;classic&quot;,
        ///          &quot;display_name&quot;: &quot;Classic&quot;
        ///        },
        ///        &quot;date&quot;: &quot;0001-01-01T00:00:00Z&quot;,
        ///        &quot;total&quot;: 0
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetPlayerDailyEntries {
            get {
                return ResourceManager.GetString("GetPlayerDailyEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;player&quot;: {
        ///    &quot;id&quot;: &quot;2&quot;,
        ///    &quot;updated_at&quot;: null,
        ///    &quot;display_name&quot;: &quot;Julianna&quot;,
        ///    &quot;avatar&quot;: null
        ///  },
        ///  &quot;total&quot;: 2,
        ///  &quot;entries&quot;: [
        ///    {
        ///      &quot;leaderboard&quot;: {
        ///        &quot;id&quot;: 739796,
        ///        &quot;updated_at&quot;: null,
        ///        &quot;display_name&quot;: null,
        ///        &quot;production&quot;: false,
        ///        &quot;product&quot;: &quot;classic&quot;,
        ///        &quot;_product&quot;: {
        ///          &quot;id&quot;: 1,
        ///          &quot;name&quot;: &quot;classic&quot;,
        ///          &quot;display_name&quot;: &quot;Classic&quot;
        ///        },
        ///        &quot;date&quot;: &quot;0001-01-01T00:00:00Z&quot;,
        ///        &quot;total&quot;: 0
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetPlayerDailyEntriesFilteredByLbids {
            get {
                return ResourceManager.GetString("GetPlayerDailyEntriesFilteredByLbids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;player&quot;: {
        ///    &quot;id&quot;: &quot;1&quot;,
        ///    &quot;updated_at&quot;: null,
        ///    &quot;display_name&quot;: &quot;Leonard&quot;,
        ///    &quot;avatar&quot;: null
        ///  },
        ///  &quot;total&quot;: 1,
        ///  &quot;entries&quot;: [
        ///    {
        ///      &quot;leaderboard&quot;: {
        ///        &quot;id&quot;: 739999,
        ///        &quot;updated_at&quot;: null,
        ///        &quot;display_name&quot;: null,
        ///        &quot;production&quot;: false,
        ///        &quot;product&quot;: &quot;classic&quot;,
        ///        &quot;_product&quot;: {
        ///          &quot;id&quot;: 1,
        ///          &quot;name&quot;: &quot;classic&quot;,
        ///          &quot;display_name&quot;: &quot;Classic&quot;
        ///        },
        ///        &quot;mode&quot;: &quot;standard&quot;,
        ///        &quot;_mode&quot;: {
        ///          &quot;id&quot;: 1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetPlayerEntries {
            get {
                return ResourceManager.GetString("GetPlayerEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;player&quot;: {
        ///    &quot;id&quot;: &quot;2&quot;,
        ///    &quot;updated_at&quot;: null,
        ///    &quot;display_name&quot;: &quot;Julianna&quot;,
        ///    &quot;avatar&quot;: null
        ///  },
        ///  &quot;total&quot;: 2,
        ///  &quot;entries&quot;: [
        ///    {
        ///      &quot;leaderboard&quot;: {
        ///        &quot;id&quot;: 739796,
        ///        &quot;updated_at&quot;: null,
        ///        &quot;display_name&quot;: null,
        ///        &quot;production&quot;: false,
        ///        &quot;product&quot;: &quot;classic&quot;,
        ///        &quot;_product&quot;: {
        ///          &quot;id&quot;: 1,
        ///          &quot;name&quot;: &quot;classic&quot;,
        ///          &quot;display_name&quot;: &quot;Classic&quot;
        ///        },
        ///        &quot;mode&quot;: &quot;standard&quot;,
        ///        &quot;_mode&quot;: {
        ///          &quot;id&quot;: 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetPlayerEntriesFilteredByLbids {
            get {
                return ResourceManager.GetString("GetPlayerEntriesFilteredByLbids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;player&quot;: {
        ///    &quot;id&quot;: &quot;2&quot;,
        ///    &quot;updated_at&quot;: null,
        ///    &quot;display_name&quot;: &quot;Julianna&quot;,
        ///    &quot;avatar&quot;: null
        ///  },
        ///  &quot;rank&quot;: 0,
        ///  &quot;score&quot;: 0,
        ///  &quot;end&quot;: {
        ///    &quot;zone&quot;: 0,
        ///    &quot;level&quot;: 0
        ///  },
        ///  &quot;killed_by&quot;: null,
        ///  &quot;version&quot;: null
        ///}.
        /// </summary>
        internal static string GetPlayerEntry {
            get {
                return ResourceManager.GetString("GetPlayerEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;total&quot;: 2,
        ///  &quot;players&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;5&quot;,
        ///      &quot;updated_at&quot;: null,
        ///      &quot;display_name&quot;: &quot;Stacey&quot;,
        ///      &quot;avatar&quot;: null
        ///    },
        ///    {
        ///      &quot;id&quot;: &quot;3&quot;,
        ///      &quot;updated_at&quot;: null,
        ///      &quot;display_name&quot;: &quot;Steve&quot;,
        ///      &quot;avatar&quot;: null
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string GetPlayers {
            get {
                return ResourceManager.GetString("GetPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;total&quot;: 3,
        ///  &quot;replays&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;25094445621522262&quot;,
        ///      &quot;error&quot;: null,
        ///      &quot;seed&quot;: null,
        ///      &quot;version&quot;: null,
        ///      &quot;killed_by&quot;: null
        ///    },
        ///    {
        ///      &quot;id&quot;: &quot;25094445622197065&quot;,
        ///      &quot;error&quot;: null,
        ///      &quot;seed&quot;: null,
        ///      &quot;version&quot;: null,
        ///      &quot;killed_by&quot;: null
        ///    },
        ///    {
        ///      &quot;id&quot;: &quot;25094445622344966&quot;,
        ///      &quot;error&quot;: null,
        ///      &quot;seed&quot;: null,
        ///      &quot;version&quot;: null,
        ///      &quot;killed_by&quot;: null
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string GetReplays {
            get {
                return ResourceManager.GetString("GetReplays", resourceCulture);
            }
        }
    }
}
