//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toofz.NecroDancer.Web.Api.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("toofz.NecroDancer.Web.Api.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;total&quot;: 8,
        ///  &quot;enemies&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;bat&quot;,
        ///      &quot;type&quot;: 1,
        ///      &quot;display_name&quot;: &quot;Bat&quot;,
        ///      &quot;health&quot;: 1,
        ///      &quot;damage&quot;: 1,
        ///      &quot;beats_per_move&quot;: 2,
        ///      &quot;drops&quot;: 2
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;dragon&quot;,
        ///      &quot;type&quot;: 2,
        ///      &quot;display_name&quot;: &quot;Dragon&quot;,
        ///      &quot;health&quot;: 6,
        ///      &quot;damage&quot;: 6,
        ///      &quot;beats_per_move&quot;: 2,
        ///      &quot;drops&quot;: 20
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;monkey&quot;,
        ///      &quot;type&quot;: 3,
        ///      &quot;display_name&quot;: &quot;Monkey&quot;,
        ///      &quot;health&quot;: 1,
        ///      &quot;damage&quot;: 0,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEnemies {
            get {
                return ResourceManager.GetString("GetEnemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;total&quot;: 1,
        ///  &quot;enemies&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;necrodancer&quot;,
        ///      &quot;type&quot;: 1,
        ///      &quot;display_name&quot;: &quot;Necrodancer&quot;,
        ///      &quot;health&quot;: 6,
        ///      &quot;damage&quot;: 3,
        ///      &quot;beats_per_move&quot;: 2,
        ///      &quot;drops&quot;: 0
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string GetEnemiesByAttribute {
            get {
                return ResourceManager.GetString("GetEnemiesByAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;total&quot;: 21,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;armor_glass&quot;,
        ///      &quot;display_name&quot;: &quot;Armor Glass&quot;,
        ///      &quot;slot&quot;: &quot;body&quot;,
        ///      &quot;unlock&quot;: 4,
        ///      &quot;cost&quot;: 50
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;feet_ballet_shoes&quot;,
        ///      &quot;display_name&quot;: &quot;Feet Ballet Shoes&quot;,
        ///      &quot;slot&quot;: &quot;feet&quot;,
        ///      &quot;unlock&quot;: null,
        ///      &quot;cost&quot;: 25
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;food_1&quot;,
        ///      &quot;display_name&quot;: &quot;Food 1&quot;,
        ///      &quot;slot&quot;: &quot;action&quot;,
        ///      &quot;unlock&quot;: null,
        ///      &quot;cost&quot;: 10
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;head_blast_helm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItems {
            get {
                return ResourceManager.GetString("GetItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;total&quot;: 1,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;armor_glass&quot;,
        ///      &quot;display_name&quot;: &quot;Armor Glass&quot;,
        ///      &quot;slot&quot;: &quot;body&quot;,
        ///      &quot;unlock&quot;: 4,
        ///      &quot;cost&quot;: 50
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string GetItemsByCategory {
            get {
                return ResourceManager.GetString("GetItemsByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;total&quot;: 1,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;weapon_blood_bow&quot;,
        ///      &quot;display_name&quot;: &quot;Weapon Blood Bow&quot;,
        ///      &quot;slot&quot;: &quot;weapon&quot;,
        ///      &quot;unlock&quot;: null,
        ///      &quot;cost&quot;: 250
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string GetItemsBySubcategory {
            get {
                return ResourceManager.GetString("GetItemsBySubcategory", resourceCulture);
            }
        }
    }
}
